
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import Link from "next/link";

export default function TermsOfServicePage() {
  return (
    <div className="flex-1 space-y-8 p-4 md:p-8">
        <div className="text-center">
            <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
            <p className="mt-2 text-lg text-muted-foreground">
                Last updated: {new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
        </div>

        <div className="container mx-auto max-w-4xl space-y-6 text-sm text-muted-foreground">
            <p className="text-base">Welcome to StudYear! These Terms of Service ("Terms") govern your use of the StudYear website, applications, and services (collectively, the "Service"). By creating an account and using our Service, you agree to be bound by these Terms. Please read them carefully.</p>

            <Card>
                <CardHeader><CardTitle className="text-xl">1. Acceptance of Terms & Our Service</CardTitle></CardHeader>
                <CardContent className="space-y-2">
                    <p>StudYear ("we", "us") provides an AI-powered academic command centre designed to help students improve their academic performance through diagnostic reports, personalised study plans, and generative AI tools. By accessing or using our Service, you confirm that you can form a binding contract with us, that you accept these Terms, and that you agree to comply with them.</p>
                </CardContent>
            </Card>

            <Card>
                <CardHeader><CardTitle className="text-xl">2. AI Credit Unit (ACU) System and Billing</CardTitle></CardHeader>
                <CardContent className="space-y-4">
                    <p>The Service's AI features are powered by a prepaid credit system using AI Credit Units (ACUs).</p>
                    <ul className="list-disc pl-5 space-y-2">
                        <li><strong>Prepaid Model:</strong> The Service operates on a strictly prepaid basis. You must have a positive ACU balance to use AI-powered features. There is no overdraft or credit facility; if your ACU balance is zero, AI features will be disabled until you top up your wallet.</li>
                        <li><strong>Consumption:</strong> Each AI feature has an associated ACU cost. When you initiate an AI-powered action, the required ACUs are debited from your wallet. This process is designed to be transparent and prevent surprise charges.</li>
                        <li><strong>Purchases & Refunds:</strong> ACUs are purchased in packs. All purchases of ACU packs are final and non-refundable. We do not provide refunds or credits for partially used packs or remaining ACU balances upon account termination.</li>
                        <li><strong>Pricing:</strong> We reserve the right to change the pricing of ACU packs and the ACU cost of features at any time.</li>
                    </ul>
                </CardContent>
            </Card>

             <Card>
                <CardHeader><CardTitle className="text-xl">3. AI Functionality and User Responsibility</CardTitle></CardHeader>
                <CardContent className="space-y-4">
                    <p>Our Service uses generative artificial intelligence to produce outputs like study plans, feedback, summaries, and predictions.</p>
                     <ul className="list-disc pl-5 space-y-2">
                        <li><strong>No Guarantee of Accuracy:</strong> AI-generated content is probabilistic and may contain inaccuracies, errors, or omissions. It is provided as a study aid and should not be considered a substitute for professional academic advice or your own critical judgment. Grade predictions are estimates based on available data and are not a guarantee of future performance.</li>
                        <li><strong>User Responsibility:</strong> You are solely responsible for reviewing, verifying, and editing any content generated by our AI before relying on it for any purpose, especially for submitting academic work. Do not submit AI-generated content as your own work without significant modification and attribution where required by your academic institution.</li>
                    </ul>
                </CardContent>
            </Card>

            <Card>
                <CardHeader><CardTitle className="text-xl">4. User Accounts and Conduct</CardTitle></CardHeader>
                <CardContent className="space-y-4">
                    <p>You are responsible for all activity that occurs under your account. You agree to:</p>
                    <ul className="list-disc pl-5 space-y-2">
                        <li>Provide accurate and complete information during registration and keep it updated.</li>
                        <li>Maintain the security of your password and accept all risks of unauthorized access to your account.</li>
                        <li>Not engage in any activity that is unlawful, fraudulent, or harmful, including uploading malicious content, scraping data, or attempting to reverse-engineer the platform.</li>
                         <li>Not share your account credentials with any other person. Account access is for the sole use of the registered individual.</li>
                    </ul>
                </CardContent>
            </Card>

            <Card>
                <CardHeader><CardTitle className="text-xl">5. Intellectual Property</CardTitle></CardHeader>
                <CardContent>
                    <p>The Service and its original content (excluding content provided by you), features, and functionality are and will remain the exclusive property of StudYear and its licensors. Content you submit for AI processing remains your property, though you grant us a license to use it to provide the Service to you. Resources you voluntarily contribute to the shared platform library may be subject to a broader license as described at the point of submission.</p>
                </CardContent>
            </Card>

            <Card>
                <CardHeader><CardTitle className="text-xl">6. Termination</CardTitle></CardHeader>
                <CardContent>
                    <p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason, including if you breach these Terms. Upon termination, your right to use the Service will cease, and any remaining ACU balance will be non-refundable.</p>
                </CardContent>
            </Card>

            <Card>
                <CardHeader><CardTitle className="text-xl">7. Disclaimers and Limitation of Liability</CardTitle></CardHeader>
                <CardContent>
                    <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We do not warrant that the Service will be uninterrupted, error-free, or that AI-generated content will meet your academic requirements. To the fullest extent permitted by law, StudYear shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or academic standing, arising from your use of the Service.</p>
                </CardContent>
            </Card>

            <Card>
                <CardHeader><CardTitle className="text-xl">8. Governing Law and Jurisdiction</CardTitle></CardHeader>
                <CardContent>
                    <p>These Terms shall be governed and construed in accordance with the laws of England and Wales, without regard to its conflict of law provisions. You agree to submit to the exclusive jurisdiction of the courts of England and Wales.</p>
                </CardContent>
            </Card>

             <Card>
                <CardHeader><CardTitle className="text-xl">9. Contact Us</CardTitle></CardHeader>
                <CardContent>
                    <p>If you have any questions about these Terms, please contact us at <Link href="mailto:contact@studyear.ai" className="text-primary underline">contact@studyear.ai</Link>.</p>
                </CardContent>
            </Card>

        </div>
    </div>
  );
}
