
import { BookOpen, FlaskConical, Atom, Landmark, Globe, Sigma, Languages, Award, BrainCircuit, HeartPulse, Building, Vote, Scale, Palette, Code, Drama, DraftingCompass, Briefcase, Search, Presentation, UserCheck, CheckSquare, FileText, FileSignature, Copy, Puzzle, Newspaper, Wand2, Bot, GraduationCap, Image, BarChartHorizontal, LineChart, PieChart, ScatterChart, AreaChart, PenTool, FileCheck2 } from "lucide-react";

/** Dedupe + alphabetical sort for stable dropdowns */
function uniqSorted(arr: readonly string[]): string[] {
    return [...new Set(arr.map((s) => s.trim()).filter(Boolean))].sort((a, b) =>
        a.localeCompare(b, undefined, { sensitivity: 'base' }),
    );
}

/** Study levels shown in profile setup (progression order). */
export const levels = [
    'Reception (Primary School)',
    'Primary School',
    'Key Stage 1: Ages 5–7 (Years 1–2)',
    'Key Stage 2: Ages 7–11 (Years 3–6)',
    'Key Stage 3: Ages 11–14 (Years 7–9)',
    'Key Stage 4: Ages 14–16 (Years 10–11)',
    '11+ Exam',
    'GCSE',
    'IGCSE',
    'AS',
    'A2/A-level',
    'BTEC',
    'BTEC National',
    'T-Level',
    'International Baccalaureate',
    'National 5',
    'Scottish Highers',
    'Scottish Advanced Highers',
    'NVQ',
    'Fun',
    'University / Degree',
    'Other',
];

/** Master subject list (UK curricula + vocational routes). */
const SUBJECT_SEED: readonly string[] = [
    'Accounting',
    'Agriculture, Environmental & Animal Care',
    'Applied Science',
    'Art and Design',
    'Biology',
    'Business & Administration',
    'Business Studies',
    'Business, Enterprise and Law',
    'Chemistry',
    'Childcare',
    'Citizenship',
    'Combined Science',
    'Computing',
    'Construction',
    'Construction & Built Environment',
    'Creative & Design',
    'Design and Technology',
    'Digital',
    'Economics',
    'Education & Childcare',
    'Engineering',
    'Engineering (e.g., Electromechanical)',
    'Engineering & Manufacturing',
    'English',
    'English Language',
    'English Literature',
    'Esports',
    'French',
    'Further Mathematics',
    'Geography',
    'German',
    'Government & Politics',
    'Health & Science',
    'Health & Social Care',
    'History',
    'Hospitality',
    'ICT',
    'IT and Computing',
    'Land-based Studies',
    'Languages',
    'Law',
    'Legal',
    'Mathematics',
    'Media and Creative Arts',
    'Media Studies',
    'Music',
    'Non-Verbal Reasoning',
    'Performing Arts',
    'Philosophy',
    'Physical Education',
    'Physics',
    'Psychology',
    'Public and Uniformed Services',
    'Relationship and Sex Education',
    'Religious Education',
    'Religious Studies',
    'Science',
    'Sociology',
    'Spanish',
    'Sport',
    'Travel and Tourism',
    'Verbal Reasoning',
    'Other',
];

export const subjects = uniqSorted(SUBJECT_SEED);

/** Exam boards / awarding organisations */
export const examBoards = [
    'AQA',
    'CACHE',
    'CCEA',
    'CEM',
    'CIE',
    'City & Guilds',
    'Edexcel',
    'GL Assessment',
    'ICAAE',
    'IMI',
    'International Boards',
    'NCFE',
    'OCR',
    'Oxford',
    'Pearson',
    'Pearson Edexcel',
    'SQA',
    'WJEC',
    'WJEC/Eduqas',
    'Other',
];

export const universityCourses = [
    "Architecture",
    "Business",
    "Civil Engineering",
    "Computer Science",
    "Construction Management",
    "Dentistry",
    "Economics",
    "Education (Teaching)",
    "Electrical Engineering",
    "Emergency Services (Fire, Police, Paramedics)",
    "Engineering",
    "English",
    "Healthcare Practice",
    "History",
    "Law",
    "Mechanical Engineering",
    "Medical Surgery",
    "Medicine",
    "Nursing",
    "Plumbing Engineering",
    "Psychiatry",
    "Psychology",
];

/**
 * Subjects available when a study level is chosen. Each level offers the full catalogue
 * so learners can match school offerings; university level also includes named degree routes.
 */
export const subjectsByLevel: Record<string, string[]> = Object.fromEntries(
    levels.map((level) => {
        if (level === 'University / Degree') {
            return [level, uniqSorted([...universityCourses, ...subjects])];
        }
        return [level, subjects];
    }),
) as Record<string, string[]>;


export const resourceMetadata = {
    'AI_COURSE': { title: "AI Courses", icon: Wand2, description: "Structured courses with modules, topics, and quizzes." },
    'AI_INTERACTIVE_LESSON': { title: "AI Interactive Lessons", icon: GraduationCap, description: "Step-by-step lessons generated by AI on any topic." },
    'AI_TUTOR_SESSION': { title: "AI Tutor Sessions", icon: Bot, description: "Saved chat sessions with the AI Tutor." },
    'DIAGNOSTIC_REPORT': { title: "Diagnostic Reports", icon: Search, description: "AI-generated academic diagnostics." },
    'ESSAY_PLAN': { title: "Essay Plans", icon: FileSignature, description: "Structured essay plans with thesis statements and arguments." },
    'FLASHCARD': { title: "Flashcards", icon: Copy, description: "Interactive flashcards for quick memory recall." },
    'FORMULA_SHEET': { title: "Formula Sheets", icon: Sigma, description: "Generate a sheet of essential formulas for a science or maths subject." },
    'MIND_MAP': { title: "Mind Maps", icon: BrainCircuit, description: "Visually organize information and show relationships between concepts." },
    'PAST_PAPER': { title: "Past Papers", icon: Newspaper, description: "Official past papers from all major exam boards." },
    'QUIZ': { title: "Quizzes", icon: Puzzle, description: "Test your knowledge with AI-generated quizzes on any topic." },
    'RECOVERY_PLAN': { title: "Recovery Plans", icon: CheckSquare, description: "Corrective intervention plans to get students back on track." },
    'STUDY_PLAN': { title: "Study Plans", icon: Presentation, description: "Personalized, AI-generated study schedules." },
    'TOPIC_SUMMARY': { title: "Summaries", icon: BookOpen, description: "Concise summaries of complex topics or large blocks of text." },
    'VIDEO': { title: "Videos", icon: BookOpen, description: "Curated educational videos from around the web." },
    
    // Visual Tools
    'VISUAL_DRAWING': { title: 'Visual Drawing', icon: PenTool, description: "Create custom drawings and diagrams from a text prompt." },
    'EDUCATIONAL_IMAGE': { title: 'Educational Image', icon: Image, description: "Generate educational images and illustrations." },
    'BAR_GRAPH': { title: 'Bar Graph', icon: BarChartHorizontal, description: "Create a bar graph from your own data." },
    'LINE_GRAPH': { title: 'Line Graph', icon: LineChart, description: "Create a line graph from your own data." },
    'PIE_CHART': { title: 'Pie Chart', icon: PieChart, description: "Create a pie chart from your own data." },
    'SCATTER_PLOT': { title: 'Scatter Plot', icon: ScatterChart, description: "Create a scatter plot from your own data." },
    'HISTOGRAM': { title: 'Histogram', icon: AreaChart, description: "Create a histogram from your own data." },
    'PICTOGRAPH': { title: 'Pictograph', icon: Palette, description: "Create a pictograph from your own data." },
    'COORDINATE_GRAPH': { title: 'Coordinate Graph', icon: DraftingCompass, description: "Create a coordinate graph." },
    'GEOMETRY_DIAGRAM': { title: 'Geometry Diagram', icon: DraftingCompass, description: "Create a geometry diagram." },
    'FUNCTION_GRAPH': { title: 'Function Graph', icon: DraftingCompass, description: "Create a function graph." },
    'GRAPH_THEORY_DIAGRAM': { title: 'Graph Theory Diagram', icon: DraftingCompass, description: "Create a graph theory diagram." },

    'ASSIGNMENT_REVIEW': { title: 'Assignment Review', icon: FileCheck2, description: "Get detailed feedback and a predicted grade on your written work." },
    'ESSAY_REVIEW': { title: 'Essay Review', icon: FileCheck2, description: "In-depth review for essays, focusing on structure and argument." },
    'DISSERTATION_REVIEW': { title: 'Dissertation Review', icon: FileCheck2, description: "Comprehensive feedback for long-form academic work like dissertations." },
};
export type ResourceType = keyof typeof resourceMetadata;

export const grades = ["9", "8", "7", "6", "5", "4", "3", "2", "1", "A*", "A", "B", "C", "D", "E", "U", "Pass", "Merit", "Distinction"];
