import {
  resourceMetadata,
  type ResourceType,
} from '@/data/academic';
import {
  BarChartHorizontal,
  BookOpen,
  BrainCircuit,
  Copy,
  FileSignature,
  GraduationCap,
  Newspaper,
  Presentation,
  Puzzle,
  Sigma,
  Wand2,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/** Not listed on Find Study Resources (private student / review content). */
export const PRIVATE_LIBRARY_RESOURCE_TYPES = new Set<ResourceType>([
  'DIAGNOSTIC_REPORT',
  'RECOVERY_PLAN',
  'AI_TUTOR_SESSION',
  'ASSIGNMENT_REVIEW',
  'ESSAY_REVIEW',
  'DISSERTATION_REVIEW',
]);

/** Categories shown on Find Study Resources (shared library only). */
export const PUBLIC_LIBRARY_RESOURCE_TYPES: ResourceType[] = (
  Object.keys(resourceMetadata) as ResourceType[]
).filter((type) => !PRIVATE_LIBRARY_RESOURCE_TYPES.has(type));

/** Chart / diagram types grouped under one hub tile. */
export const VISUAL_TOOL_RESOURCE_TYPES: ResourceType[] = [
  'VISUAL_DRAWING',
  'EDUCATIONAL_IMAGE',
  'BAR_GRAPH',
  'LINE_GRAPH',
  'PIE_CHART',
  'SCATTER_PLOT',
  'HISTOGRAM',
  'PICTOGRAPH',
  'COORDINATE_GRAPH',
  'GEOMETRY_DIAGRAM',
  'FUNCTION_GRAPH',
  'GRAPH_THEORY_DIAGRAM',
];

export type LibraryHubSection = {
  id: string;
  title: string;
  description: string;
  icon: LucideIcon;
  href: string;
  resourceTypes: ResourceType[];
};

/** Student-facing hub sections — avoids 20+ separate chart tiles. */
export const LIBRARY_HUB_SECTIONS: LibraryHubSection[] = [
  {
    id: 'QUIZ',
    title: 'Quizzes',
    description: 'Test your knowledge with AI-generated quizzes on any topic.',
    icon: Puzzle,
    href: '/resources?type=QUIZ',
    resourceTypes: ['QUIZ'],
  },
  {
    id: 'FLASHCARD',
    title: 'Flashcards',
    description: 'Interactive flashcards for quick memory recall.',
    icon: Copy,
    href: '/resources?type=FLASHCARD',
    resourceTypes: ['FLASHCARD'],
  },
  {
    id: 'TOPIC_SUMMARY',
    title: 'Summaries',
    description: 'Concise summaries of complex topics.',
    icon: BookOpen,
    href: '/resources?type=TOPIC_SUMMARY',
    resourceTypes: ['TOPIC_SUMMARY'],
  },
  {
    id: 'MIND_MAP',
    title: 'Mind Maps',
    description: 'Visually organise information and show relationships.',
    icon: BrainCircuit,
    href: '/resources?type=MIND_MAP',
    resourceTypes: ['MIND_MAP'],
  },
  {
    id: 'FORMULA_SHEET',
    title: 'Formula Sheets',
    description: 'Essential formulas for science and maths subjects.',
    icon: Sigma,
    href: '/resources?type=FORMULA_SHEET',
    resourceTypes: ['FORMULA_SHEET'],
  },
  {
    id: 'STUDY_PLAN',
    title: 'Study Plans',
    description: 'Personalised AI-generated study schedules.',
    icon: Presentation,
    href: '/resources?type=STUDY_PLAN',
    resourceTypes: ['STUDY_PLAN'],
  },
  {
    id: 'ESSAY_PLAN',
    title: 'Essay Plans',
    description: 'Structured essay plans with thesis and arguments.',
    icon: FileSignature,
    href: '/resources?type=ESSAY_PLAN',
    resourceTypes: ['ESSAY_PLAN'],
  },
  {
    id: 'AI_COURSE',
    title: 'AI Courses',
    description: 'Structured courses with modules, topics, and quizzes.',
    icon: Wand2,
    href: '/resources?type=AI_COURSE',
    resourceTypes: ['AI_COURSE'],
  },
  {
    id: 'AI_INTERACTIVE_LESSON',
    title: 'Interactive Lessons',
    description: 'Step-by-step lessons generated by AI on any topic.',
    icon: GraduationCap,
    href: '/resources?type=AI_INTERACTIVE_LESSON',
    resourceTypes: ['AI_INTERACTIVE_LESSON'],
  },
  {
    id: 'VIDEO',
    title: 'Videos',
    description: 'Curated educational videos from around the web.',
    icon: BookOpen,
    href: '/resources?type=VIDEO',
    resourceTypes: ['VIDEO'],
  },
  {
    id: 'PAST_PAPER',
    title: 'Past Papers',
    description: 'Official past papers from major exam boards.',
    icon: Newspaper,
    href: '/resources?type=PAST_PAPER',
    resourceTypes: ['PAST_PAPER'],
  },
  {
    id: 'VISUAL_TOOLS',
    title: 'Visual Tools & Graphs',
    description: 'Bar charts, pie charts, diagrams, and labelled educational images.',
    icon: BarChartHorizontal,
    href: '/resources?type=VISUAL_TOOLS',
    resourceTypes: VISUAL_TOOL_RESOURCE_TYPES,
  },
];

export function hubSectionCount(
  section: LibraryHubSection,
  counts: Record<string, number>,
): number {
  return section.resourceTypes.reduce((sum, t) => sum + (counts[t] ?? 0), 0);
}
