
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertCircle, BrainCircuit, UserCheck } from "lucide-react";

export default function DisclaimerPage() {
  return (
    <div className="flex-1 space-y-8 p-4 md:p-8">
        <div className="text-center">
            <h1 className="text-4xl font-bold tracking-tight">Disclaimer</h1>
            <p className="mt-2 text-lg text-muted-foreground">
                Last updated: {new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
        </div>

        <div className="container mx-auto max-w-4xl space-y-6 text-sm text-muted-foreground">
            <p className="text-base">The information, tools, and AI-generated content provided by StudYear (the "Service") are for informational and educational purposes only. By using our Service, you acknowledge and agree to the following:</p>

            <Card>
                <CardHeader><CardTitle className="text-xl flex items-center gap-2"><BrainCircuit className="text-primary"/>AI-Generated Content</CardTitle></CardHeader>
                <CardContent className="space-y-4">
                    <p>Our Service utilises artificial intelligence to generate content, including but not limited to study plans, topic summaries, essay feedback, and grade predictions. You understand that:</p>
                    <ul className="list-disc pl-5 space-y-2">
                        <li><strong>Outputs are Probabilistic:</strong> AI models are probabilistic systems. The content they generate may contain inaccuracies, errors, or outdated information. It does not constitute professional, certified, or guaranteed advice.</li>
                        <li><strong>No Guarantee of Accuracy:</strong> We make no warranties or representations regarding the completeness, accuracy, reliability, or suitability of any AI-generated content. Grade predictions are estimates based on available data and are not a guarantee of future performance.</li>
                        <li><strong>For Educational Aid Only:</strong> All content should be treated as a first draft or a study aid, not as a final, authoritative answer.</li>
                    </ul>
                </CardContent>
            </Card>

            <Card>
                <CardHeader><CardTitle className="text-xl flex items-center gap-2"><UserCheck className="text-primary"/>User Responsibility</CardTitle></CardHeader>
                <CardContent className="space-y-4">
                    <p>The ultimate responsibility for your academic work and outcomes rests with you. You agree that:</p>
                     <ul className="list-disc pl-5 space-y-2">
                        <li>You will critically review, verify, and edit all information and content generated by the Service before relying on it for any purpose, especially for submitting academic work.</li>
                        <li>You will adhere to the academic integrity policies of your institution. Submitting AI-generated content as your own work without proper attribution or significant original contribution may constitute academic misconduct.</li>
                        <li>Your use of the Service is at your own risk. StudYear is not responsible for any academic or other consequences that may arise from your use of the content provided.</li>
                    </ul>
                </CardContent>
            </Card>

             <Card>
                <CardHeader><CardTitle className="text-xl flex items-center gap-2"><AlertCircle className="text-primary"/>No Professional Advice</CardTitle></CardHeader>
                <CardContent>
                    <p>The Service is not a substitute for professional academic advice from qualified educators, tutors, or guidance counsellors. It is a supplementary tool designed to support your own study efforts. We do not provide accredited educational services.</p>
                </CardContent>
            </Card>
        </div>
    </div>
  );
}
